---
title: "Organization Types"
author: "J Andres Gannon"
date: "May 2020"
output: html_document
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
```

# Load Data
```{r}
df_nodes <- googlesheets4::read_sheet(ss = "https://docs.google.com/spreadsheets/d/1pBLRXoUovjBy_1vYIIV9Ib7YGZfBJqIOIOOKkA1YTIs/edit?usp=sharing",
                                    sheet = "WH_outOrganisations_conections")
head(df_nodes)

df_id <- googlesheets4::read_sheet(ss = "https://docs.google.com/spreadsheets/d/1pBLRXoUovjBy_1vYIIV9Ib7YGZfBJqIOIOOKkA1YTIs/edit?usp=sharing",
                                    sheet = "wikidata_id")
head(df_id)

df_wiki <- googlesheets4::read_sheet(ss = "https://docs.google.com/spreadsheets/d/1pBLRXoUovjBy_1vYIIV9Ib7YGZfBJqIOIOOKkA1YTIs/edit?usp=sharing",
                                    sheet = "wikidata_sparql_query")
head(df_wiki)
```

# Prep
Merge the IDs into the node list
```{r}
df_nodes <- dplyr::left_join(df_nodes, df_id)
```

Extract wikidata IDs from SPARQL query for easier merging
```{r}
df_wiki$id <- sub(".*entity/", "", df_wiki$item)
```

Subset wiki query to qualities of interest
```{r}
df_wiki <- df_wiki %>% dplyr::select(c("id", "itemLabel", "classLabel", "coordinate_location", "legal_formLabel", "headquarters_locationLabel"))
df_wiki <- unique(df_wiki)

# Collapse classLabels
df_wiki$classLabel_condense <- df_wiki$classLabel
sort(unique(df_wiki$classLabel_condense))

## Fix universities
df_wiki$classLabel_condense[df_wiki$classLabel == "Catholic university" |
                             df_wiki$classLabel == "Colonial Colleges" |
                             df_wiki$classLabel == "law school" |
                             df_wiki$classLabel == "private university" |
                             df_wiki$classLabel == "public educational institution of the United States" |
                             df_wiki$classLabel == "private not-for-profit educational institution" |
                             df_wiki$classLabel == "open-access publisher" |
                             df_wiki$classLabel == "research university"] <- "university"

## Fix government
df_wiki$classLabel_condense[df_wiki$classLabel == "campaign committee" |
                             df_wiki$classLabel == "Hill committee" |
                             df_wiki$classLabel == "political party committee" |
                             df_wiki$classLabel == "senate" |
                             df_wiki$classLabel == "upper house of U.S. state legislature" |
                             df_wiki$classLabel == "state of the United States"] <- "government"

## Fix defense contractors
df_wiki$classLabel_condense[df_wiki$classLabel == "aerospace manufacturer" |
                             df_wiki$classLabel == "defense contractor" |
                             df_wiki$classLabel == "enterprise"] <- "defense contractor"

## Fix media
df_wiki$classLabel_condense[df_wiki$classLabel == "pay television" |
                             df_wiki$classLabel == "specialty channel" |
                             df_wiki$classLabel == "TV production company" |
                             df_wiki$classLabel == "United States cable news" |
                             df_wiki$classLabel == "website"] <- "media"

## Fix non profit
df_wiki$classLabel_condense[df_wiki$classLabel == "advocacy group" |
                             df_wiki$classLabel == "nonprofit organization" |
                             df_wiki$classLabel == "organization"] <- "non-profit"
## Fix public company
df_wiki$classLabel_condense[df_wiki$classLabel == "Aplicación Ilegal En Bolivia" |
                             df_wiki$classLabel == "business" |
                             df_wiki$classLabel == "data controller" |
                             df_wiki$classLabel == "enterprise" |
                             df_wiki$classLabel == "public company" |
                             df_wiki$classLabel == "research institute" |
                             df_wiki$classLabel == "software" |
                             df_wiki$classLabel == "think tank"] <- "private company"

# Collapse to unique
df_wiki <- df_wiki %>% dplyr::select(-c("classLabel", "legal_formLabel"))
df_wiki <- unique(df_wiki)

df_wiki$itemLabel

# Fix edge cases
df_wiki <- df_wiki %>% dplyr::filter(!(itemLabel == "American Enterprise Institute" & classLabel_condense == "non-profit"))
df_wiki <- df_wiki %>% dplyr::filter(!(itemLabel == "Georgetown University Law Center" & classLabel_condense == "university"))
df_wiki <- df_wiki %>% dplyr::filter(!(itemLabel == "Boeing" & classLabel_condense == "private company"))
df_wiki <- df_wiki %>% dplyr::filter(!(itemLabel == "Johns Hopkins University" & classLabel_condense == "private company"))
df_wiki <- df_wiki %>% dplyr::filter(!(itemLabel == "Raytheon Company" & classLabel_condense == "private company"))
df_wiki <- df_wiki %>% dplyr::filter(!(itemLabel == "Texas Public Policy Foundation" & coordinate_location == "Point(-97.741466 30.270958)"))
```

# Visualize
## Bar plot of distribution by type
```{r, fig.width=16, fig.height=8}
ggplot(df_wiki, aes(classLabel_condense, ..count..)) + 
  geom_bar() + 
  labs(title = "Groups with documented White House connections", x = "Group Type", y = "Number of Groups", fill = "") + 
  geom_text(stat = 'count', aes(label = ..count..), vjust = -1, size = 6) +
  theme(plot.title = element_text(hjust = 0.5),panel.grid = element_blank(),
        text = element_text(size = 24))
```

## Locations
```{r}
# Start with provided lat-longs
df_wiki <- tidyr::separate(df_wiki, coordinate_location, c('lat', 'lon'), sep = " ", remove = TRUE)
df_wiki$lat <- gsub("[^0-9.-]", "", df_wiki$lat)
df_wiki$lon <- gsub("[^0-9.-]", "", df_wiki$lon)

ggplot(data = df_wiki) +
    geom_point(data = df_wiki, aes(x = lon, y = lat), size = 4, shape = 23, fill = "darkred") +
    coord_sf(expand = FALSE)

# Get lat-longs for city locations
ggmap::register_google("AIzaSyA_KWTGsDPcY1lRI2fUKtUuwsACpkXnpjc")
ggmap::ggmap_hide_api_key()

locations <- df_wiki$headquarters_locationLabel
locations <- locations[!is.na(locations)]
locations <- as.data.frame(locations)

locations <- ggmap::mutate_geocode(locations, locations)

map <- dplyr::left_join(df_wiki, locations, by = c("headquarters_locationLabel" = "locations"))

# map <- map %>% dplyr::coalesce(lat.x, lat.y)
# make it interactive with pop up display about the nodes

map <- unique(map)

head(map)
```