---
title: "Prosecutors"
author: "J Andres Gannon, Katelyn Hess, and Yulia Krylova"
date: "May 2020"
output:
  html_document:
    toc: yes
    toc_float: yes
  pdf_document:
    toc: yes
  html_notebook:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: inline
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(magrittr)
library(ggplot2)
```

# Base data
## Load
```{r message = FALSE}
df_agencies <- read.csv(file = paste0(here::here(), '/network_WH_outOrganisations/trumptown_data-store_1019/agencies.csv'))
df_outside <- read.csv(file = paste0(here::here(), '/network_WH_outOrganisations/trumptown_data-store_1019/outside_government_positions.csv'))
df_staffers <- read.csv(file = paste0(here::here(), '/network_WH_outOrganisations/trumptown_data-store_1019/staffers.csv'))


df_agencies <- janitor::clean_names(df_agencies)
df_outside <- janitor::clean_names(df_outside)
df_staffers <- janitor::clean_names(df_staffers)
```

## Merge
```{r, fig.width = 16, fig.height = 16, warning = FALSE}

```

## Clean
```{r}

```

## Save
Save this version of the data as a new sheet on the original googledoc
```{r, message = FALSE}
googlesheets4::write_sheet(df_full, ss = "https://docs.google.com/spreadsheets/d/1hPOBOyTujUReQzpjZ9PqIhj23V5C74EygMnmXIi6BgI/edit?usp=sharing",
                           sheet = "mergedcode_justicedept_noedit")
df_full <- write.csv(df_full, paste0(here::here(), "/TrumpProsecutors_network/", "justicedept_merged.csv"))
```

# Employment
## Load
```{r}
work <- googlesheets4::read_sheet(ss = "https://docs.google.com/spreadsheets/d/1hPOBOyTujUReQzpjZ9PqIhj23V5C74EygMnmXIi6BgI/edit?usp=sharing",
                                    sheet = "employment_justicedepartment")

work <- janitor::clean_names(work)
```

## Clean
```{r}
# Check any notes
unique(work$notes)
work$notes <- NULL

# Check employer strings
sort(unique(work$employer))

# Fix start and end date
work$start_date[work$start_date == "Unknown"] <- NA
work$end_date[work$end_date == "Unknown"] <- NA
```

## Prep for network
```{r}
# Places of employment with the most unique attorneys
work_count <- work %>% dplyr::select(attorney, employer) %>%
  dplyr::distinct() %>%
  dplyr::group_by(employer) %>%
  dplyr::summarise(count = dplyr::n()) %>%
  dplyr::filter(count > 1)

DT::datatable(work_count)
```

## Save
````{r}
work <- work %>% dplyr::select(attorney, employer)
googlesheets4::write_sheet(work, ss = "https://docs.google.com/spreadsheets/d/1hPOBOyTujUReQzpjZ9PqIhj23V5C74EygMnmXIi6BgI/edit?usp=sharing",
                           sheet = "justicedepartmentprosecutors_noedit")

work <- write.csv(work, paste0(here::here(), "/network_WH_outOrganisations/", "justicedept_employment_hist.csv"))
```

# School
## Load
```{r}
edu <- googlesheets4::read_sheet(ss = "https://docs.google.com/spreadsheets/d/1hPOBOyTujUReQzpjZ9PqIhj23V5C74EygMnmXIi6BgI/edit?usp=sharing",
                                    sheet = "school_justicedepartment")

edu <- janitor::clean_names(edu)
```

### Temp
```{r}
work <- work %>% dplyr::select(attorney) %>%
  dplyr::distinct()
work$existing <- 1

edu <- edu %>% dplyr::select(item_label) %>%
  dplyr::distinct()

combo <- dplyr::left_join(edu, work, by = c("item_label" = "attorney"))

combo <- combo[is.na(combo$existing), ]
combo <- write.csv(combo, paste0(here::here(), "/TrumpProsecutors_network/", "combo.csv"))

```

## Clean
```{r}
## Collapse degrees
sort(unique(edu$degree))

edu$degree[edu$degree == "AA" |
             edu$degree == "AB" |
             edu$degree == "BA" |
             edu$degree == "BBA" |
             edu$degree == "BS"] <- "bachelors"
 
edu$degree[edu$degree == "LLM" |
             edu$degree == "MA" |
             edu$degree == "MBA" |
             edu$degree == "MMgt" |
             edu$degree == "MPA" |
             edu$degree == "MPhil" |
             edu$degree == "MS"] <- "masters"

edu$degree[edu$degree == "PhD" |
             edu$degree == "EdD"] <- "doctorate"

edu$degree[edu$degree == "JD" |
             edu$degree == "LLB"] <- "law"

sort(unique(edu$degree))
```

## Prep for network
```{r}
# Make wide
edu_clean <- edu %>% dplyr::select(item_label, educated_at_label, degree) %>%
  tidyr::spread(degree, educated_at_label) %>%
  dplyr::select(item_label, bachelors, masters, law, doctorate)

edu_merge <- edu %>% dplyr::select(educated_at_label, law_rank, law_conservative_score)

edu_all <- dplyr::left_join(edu_clean, edu_merge, by = c("law" = "educated_at_label")) %>%
  dplyr::distinct()

# Clean each school col
sort(unique(edu_all$bachelors))
sort(unique(edu_all$masters))
sort(unique(edu_all$law))
```

## Results
```{r}
DT::datatable(edu_all)

GGally::ggpairs(edu_all[ , c('law_rank', 'law_conservative_score')], columnLabels = c("Law School Rank", "Law School Conservatism"))
ggplot2::ggsave("law_school_corr.png", path = paste0(here::here(), '/TrumpProsecutors_network'))
```

## Save
```{r}
googlesheets4::write_sheet(edu_all, ss = "https://docs.google.com/spreadsheets/d/1hPOBOyTujUReQzpjZ9PqIhj23V5C74EygMnmXIi6BgI/edit?usp=sharing",
                           sheet = "schooljusticedepartment_noedit")

edu <- write.csv(edu_all, paste0(here::here(), "/network_WH_outOrganisations/", "justicedept_edu_hist.csv"))
```
